services:
  spondbot:
    build: .
    container_name: spondbot
    restart: unless-stopped
    ports:
      - "8888:8000"
    volumes:
      - ./data:/data
    environment:
      - LOG_LEVEL=INFO
      - DEBUG=1
      - CF_TEAM_DOMAIN=dennisnas.cloudflareaccess.com
      - CF_AUD=ce43356bf2239a9581730eb86514df7e25099e39ba819376b297c06bf78d0c13
      - CF_ADMIN_EMAILS=dpremoli1@sheffield.ac.uk
    networks:
      - bridge
      - proxy
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/dpremoli/SpondBot/refs/heads/main/logo.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8888]"

networks:
  bridge:
    external: true
  proxy:
    external: true
